services:
  medical-record-system:
    image: medical-record-system
    container_name: medical-record-system
    ports:
      - "8420:8080"
    build:
      context: .
      dockerfile: Medical-Record-System/Dockerfile
    networks:
      - medical-record-system
    depends_on:
      - rabbitmq

  medical-record-event-store:
    image: postgres:16-alpine
    container_name: medical-record-event-store
    ports:
      - "5420:5432"
    volumes:
      - ~/apps/postgres/medical:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=medical-record-event-store
    networks:
      - medical-record-system
        
  user-management:
    image: user-management
    container_name: user-management
    ports:
      - "8421:8080"
    build:
      context: .
      dockerfile: User-Management/Dockerfile
    networks:
      - medical-record-system
  
  user-management-db:
    image: postgres:16-alpine
    container_name: user-management-db
    ports:
      - "5421:5432"
    volumes:
      - ~/apps/postgres/user:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user-management-db
    networks:
      - medical-record-system
  
  appointment-planner:
    image: appointment-planner
    container_name: appointment-planner
    ports:
      - "8422:8080"
    build:
      context: .
      dockerfile: Appointment-Planner/Dockerfile
    networks:
      - medical-record-system
        
  appointment-planner-db:
    image: postgres:16-alpine
    container_name: appointment-planner-db
    ports:
      - "5422:5432"
    volumes:
      - ~/apps/postgres/appointment:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=appointment-planner-db
    networks:
      - medical-record-system
  
  notification-sender:
    image: notification-sender
    container_name: notification-sender
    ports:
      - "8423:8080"
    build:
      context: .
      dockerfile: Notification-Sender/Dockerfile
    networks:
      - medical-record-system

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # RabbitMQ main port
      - "15672:15672" # RabbitMQ management UI
    networks:
      - medical-record-system

networks:
  medical-record-system:
    driver: bridge